-- 1. Roles Table
CREATE TABLE IF NOT EXISTS roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    name VARCHAR(50) UNIQUE NOT NULL,
    description VARCHAR(255)
);

-- 2. Seed Default Roles
-- Note: UUIDs will be auto-generated by the DEFAULT clause
INSERT INTO roles (name, description) VALUES
    ('ROLE_PASSENGER', 'Standard ride requester'),
    ('ROLE_DRIVER', 'Cab driver'),
    ('ROLE_ADMIN', 'System administrator')
    ON CONFLICT (name) DO NOTHING;

-- 3. Account Table (Authentication credentials)
CREATE TABLE IF NOT EXISTS accounts (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    username VARCHAR(255) UNIQUE NOT NULL,
    password TEXT NOT NULL
);

-- 4. Account-Role Association Table (Many-to-Many relationship)
CREATE TABLE IF NOT EXISTS account_roles (
    account_id UUID REFERENCES accounts(id) ON DELETE CASCADE,
    role_id UUID REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (account_id, role_id)
);

-- 5. Create Enum Gender
DO $$ BEGIN
    CREATE TYPE gender AS ENUM (
        'MALE',
        'FEMALE',
        'OTHER'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 5. Passenger Table (Profile linked to Account)
CREATE TABLE IF NOT EXISTS passengers (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ,

    account_id UUID UNIQUE NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,

    name VARCHAR(255),
    gender gender,
    date_of_birth DATE,
    phone_number VARCHAR(20)
);
CREATE INDEX IF NOT EXISTS idx_passengers_account ON passengers(account_id);

-- 6. Driver Table (Profile linked to Account)
CREATE TABLE IF NOT EXISTS drivers (
    id              UUID PRIMARY KEY,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now(),
    deleted_at      TIMESTAMPTZ,

    account_id      UUID UNIQUE NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,


    name            VARCHAR(255),
    gender          gender,
    date_of_birth   DATE,
    phone_number    VARCHAR(20),
    license_details VARCHAR(255),
    is_available    BOOLEAN     DEFAULT false,
    active_city     VARCHAR(100)
);
CREATE INDEX IF NOT EXISTS idx_drivers_account ON drivers(account_id);

-- 7. Cars Table
CREATE TABLE IF NOT EXISTS cars (
    id              UUID PRIMARY KEY,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now(),
    deleted_at      TIMESTAMPTZ,

    driver_id       UUID UNIQUE NOT NULL REFERENCES drivers (id) ON DELETE CASCADE,

    plate_number    VARCHAR(50) UNIQUE NOT NULL,
    brand_and_model VARCHAR(100),
    color           VARCHAR(50),
    car_type        VARCHAR(50)
);